# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt
      - name: Create save and lof directories
        run: |
          mkdir .log
          mkdir saves
      - name: flake8 on hotels and tests
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./hotels ./tests --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./hotels ./tests --count --max-complexity=10 --max-line-length=127 --statistics

      - name: PyDocStyle on hotels and tests
        run: |
          pydocstyle ./hotels ./tests --ignore=D2,D107,D105

      - name: Test with unittest
        run: |
          coverage run -m unittest discover

      - name: Test coverage above 70%
        run: |
          coverage report --omit='*/venv/*','*/__init__.py','*/tests/*' --fail-under=70
